### ISSUE TITLE
[Feat]: Allow creating agents with JSON or YAML script.

### ISSUE THREAD

**Issue by samyakkkk** [Welltested-AI/fluttergpt#315]
### Describe the problem and solution that you'd like.

This is a proposal to move away from our dart framework to open up agent authoring to everyone.

1. The agent structure should be definable in YAML or JSON. 
2. Still use a CLI for publishing but something that is easily installable, like from brew in Mac. 
3. The agent.yaml file can be added to a GitHub repo and create a GitHub action that can just publish the agent.

example configuration:
```yaml
name: agent_name
avatar: avatar_path or url
description: agent_description
system_prompt: system_prompt
sources:
  sitemaps:
    https://x.com/sitemap.xml
  webpages:
    https://x.com/blog/xyz
      deepCrawl: false
    https://x.com/docs/
      deepCrawl: true
  github:
    https://github.com/CommandDash/commanddash/
      issues: false
```
above is just a guideline.

For authentication, we can still use a CLI, but I'm not sure how that would work in a GitHub action since webpage redirection won't work. So figure out an alternative solution. Maybe using a GitHub access token and putting it in the secrets.

This should automatically also create an account of user associated with the GitHub access token in our DB - and allow user to use the agent in private mode.
